name: CI - Prueba y Compilacion

on:
  pull_request:
    branches: [ "main" ]

jobs:
  construir_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  publicar_jobs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify and Package
        run: mvn --batch-mode --update-snapshots verify

      - name: Copiar archivos
        run: mkdir staging && cp target/*.jar staging

      - name: Subir artefacto
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
